### ISSUE TITLE
Allow a single entry point

### ISSUE THREAD

**Issue by brookeangel** [NoRedInk/rails_edge_test#1]
It would be super cool if rails_edge_test could regenerate JSON blobs for a single entry point, so you don't need to regenerate all the blobs at once!

**Comment by jleven** [comment]
This is mostly fixed in version 0.3.0

Would you like to add the ability to specify a line number as well?

**Comment by brookeangel** [comment]
Woo! Thank you Josh!!! 🎉 This is perfect for my purposes. 👍

**Comment by jleven** [comment]
Thank you, @brookeangel - you did all the hard work! I just moved your code around a bit.
