### ISSUE TITLE
CLI should accept real file names

### ISSUE THREAD

**Issue by avh4** [NoRedInk/rails_edge_test#7]
`./edge/spec/my_controller_edge.rb` is the file containing my edge definition.

I would expect to be able to run `bundle exec generate_edges edge/spec/my_controller_edge.rb`, since that is that real path to the file.  But currently that will not find the file (I have to do `bundle exec generate_edges my_controller_edge.rb` instead).

**Comment by brookeangel** [comment]
Relevant code is https://github.com/NoRedInk/rails_edge_test/blob/master/lib/rails_edge_test/runner.rb#L18-L21

**Comment by Arkham** [comment]
This now works :)

**Comment by avh4** [comment]
Thanks!!
